name: Test successful runs

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  empty:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          snaps:
  basic:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          snaps: |
            codespell
            astral-ty --channel=latest/edge
            ruff --channel=latest/candidate
      - name: Check snaps are installed
        run: |
          /snap/bin/codespell --version
          /snap/bin/astral-ty.ty --version
          /snap/bin/ruff --version
          snap info codespell
          snap info astral-ty
          snap info ruff
  huge:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          snaps: |
            google-cloud-sdk
  huge-again:
    needs: [huge]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          snaps: |
            google-cloud-sdk

