name: Test successful runs

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  basic:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          snaps: |
            codespell
            astral-ty --channel=latest/edge
            ruff --channel=latest/candidate
            snapcraft
      - name: Check snaps are installed
        run: |
          /snap/bin/codespell --version
          /snap/bin/astral-ty.ty --version
          /snap/bin/ruff --version
          /snap/bin/snapcraft --version
          snap info codespell
          snap info astral-ty
          snap info ruff
          snap info snapcraft
  basic-speed-compare:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          sudo snap install codespell
          sudo snap install astral-ty --channel=latest/edge
          sudo snap install ruff --channel=latest/candidate
          sudo snap install snapcraft --classic
      - name: Check snaps are installed
        run: |
          /snap/bin/codespell --version
          /snap/bin/astral-ty.ty --version
          /snap/bin/ruff --version
          /snap/bin/snapcraft --version
          snap info codespell
          snap info astral-ty
          snap info ruff
          snap info snapcraft

  huge:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          snaps: |
            google-cloud-sdk
  huge-speed-compare:
    runs-on: ubuntu-24.04
    steps:
      - run: |
         sudo snap install google-cloud-sdk --classic

